/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9qv8uTHD3Zo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { ModelSelect } from "./model-select"



export function Main() {
  return (
    <div className="w-full min-h-screen bg-background text-foreground">
      <header className="py-6 px-4 md:px-6 border-b">
        <div className="container flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="text-xl font-semibold">AI Cover Generator</span>
          </Link>

          <Button>Get Started</Button>
        </div>
      </header>
      <main className="py-12 md:py-24 px-4 md:px-6">
        <div className="container grid md:grid-cols-2 gap-12">
          <div className="space-y-6">
            <h1 className="text-4xl md:text-5xl font-bold">Generate AI-Powered YouTube Cover Images</h1>
            <p className="text-muted-foreground text-lg">
              Create stunning cover images for your YouTube videos using our advanced AI technology.
            </p>
            <form className="space-y-4">
              <div>
                <Label htmlFor="video-url">YouTube Video URL</Label>
                <Input id="video-url" type="text" placeholder="https://www.youtube.com/watch?v=dQw4w9WgXcQ" />
              </div>
              <div>
                <ModelSelect/>
              </div>
              <div>
                <Label htmlFor="conversion-type">Conversion Type</Label>
                <Select>
                    <SelectTrigger className="w-[180px]">
                      <SelectValue placeholder="conversion" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="male to male">male to male</SelectItem>
                      <SelectItem value="male to female">male to female</SelectItem>
                      <SelectItem value="female to female">female to female</SelectItem>
                      <SelectItem value="female to male">female to male</SelectItem>
                    </SelectContent>
                </Select>
              </div>
              <Button type="submit" className="w-full">
                Generate Cover Image
              </Button>
            </form>
          </div>
          <div className="flex flex-col items-center justify-center">
            <div className="bg-muted rounded-xl overflow-hidden w-full max-w-md aspect-video">
              <img
                src="/placeholder.svg"
                alt="Generated Cover Image"
                width={1280}
                height={720}
                className="w-full h-full object-cover"
              />
            </div>
            <div className="mt-4 flex gap-2">
              <Button variant="outline">Download</Button>
              <Button variant="outline">Share</Button>
            </div>
          </div>
        </div>
      </main>
      <footer className="py-6 px-4 md:px-6 border-t">
        <div className="container flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-xs text-muted-foreground">&copy; 2024 AI Cover Generator. All rights reserved.</p>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-xs hover:underline" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="text-xs hover:underline" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-xs hover:underline" prefetch={false}>
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
